### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by lasse1977** [khugo/JShark#1]
# Katselmointi 1
Koodi ladattu 20.11.2016 8:48

## PIT-raportti

PIT-testaus ok. Kattavuus on tähän mennessä oikealla tolalla.

## Checkstyle

Checkstylen osalta niin ikään kaikki kunnossa.

## Yleistä

Ohjelman avaaminen onnistuu kyllä ja käyttäjänä saan tiedon liikenteestä aihekuvauksen mukaisesti, mikäli nyt täysin ymmärsin mitä ohjemalta odottaa. Tiedostonkäsittely on ilmeisesti vielä vaiheessa, koska näitä tallenus-/lataustoimintoja ei vielä pystynyt käyttämään.

## Logiikka

Ohjelman logiikka sisälsi paljon koodia, josta en ymmärtänyt paljoakaan OhPe-OhJa-OhMe-kurssien asioiden pohjalta, joten logiikkariveistä ja niiden toimivuudesta on hiukan vaikea antaa palautetta. Ihan ns. Mutu-tuntumalta rivit tuntuvat kyllä loogisilta, enkä löydä juurikaan parannettavaa. AnyFieldContains-metodissa kuitenkin pisti silmään "palauta se tai se tai se tai se tai se.....". En tosin osaa sanoa voisiko siinä käyttää jotain apumuuttujaa tai vastaavaa. Saattaa olla jopa makuasia.

## Testit

Testejä ei pystynyt netBeansissä ajamaan. Projektista ei löydy TestPackages-kansiota vaan testiluokat ovat kansiossa OtherSources ja syy etteivät ole ajettavissa voi löytyä myös allekirjoittaneesta, koska itse olet kuitenkin ne pystynyt Pit-raportin perusteella ajamaan. Käsittääkseni kurssin tarkoituksena on kuitenkin soveltaa OhJa:n ja OhMe:n oppeja, jolloin pakkaukset yms olisi hyvä ehkä olla vain näiden kurssien suorittaneidenkin silmissä "ymmärrettäviä". Testien ja itse ohjelman toimivuuten nämä nyt luonnollisestikaan ei vaikuta.

**Comment by khugo** [comment]
Moi Lasse,

Kiitos palautteesta! Harmi että testejä ei pystynyt suorittamaan, en itse nimittäin käytä Netbeansia niin en tiennyt että se ei osaa avata niitä :/ Koska tämä on maven projekti, testit voi suorittaa ainakin komennolla `mvn test`, laitankin tämän heti README:n käyttöohjeisiin.

Harmi myös että jouduit näkemään projektini tilassa jossa siinä ei oikeastaan ollut mitään konkreettista valmiina, juuri tänään sain tehtyä GUI:n jossa oikeasti näkyy mitä tapahtuu :D 

AnyFieldContains-metodista tuli tosiaan hyvin sotkuista, kuten myös fieldEquals-metodista mutta en ainakaan itse oikeastaan keksi mitään parempaa tapaa tähän...

**Comment by khugo** [comment]
Hupsista, olinkin näköjään laittanut testit väärän kansion alle. Hyvä kun huomasit!
